SELECT
click_id,
ip,
app,
click_diff_1, click_diff_2, click_diff_3, click_diff_4, click_diff_5,
avg_ipdayhour,
LAG(avg_ipdayhour, 1) OVER(partition by ip order by click_time) avg_ipdayhour_1,
LAG(avg_ipdayhour, 2) OVER(partition by ip order by click_time) avg_ipdayhour_2,
LAG(avg_ipdayhour, 3) OVER(partition by ip order by click_time) avg_ipdayhour_3,
LAG(avg_ipdayhour, 4) OVER(partition by ip order by click_time) avg_ipdayhour_4,
avg_ip,
LAG(avg_ip, 1) OVER(partition by ip order by click_time) avg_ip_1,
LAG(avg_ip, 2) OVER(partition by ip order by click_time) avg_ip_2,
LAG(avg_ip, 3) OVER(partition by ip order by click_time) avg_ip_3,
LAG(avg_ip, 4) OVER(partition by ip order by click_time) avg_ip_4,
LAG(app, 1) OVER(partition by ip order by click_time) app_1,
LAG(app, 2) OVER(partition by ip order by click_time) app_2,
LAG(app, 3) OVER(partition by ip order by click_time) app_3,
LAG(app, 4) OVER(partition by ip order by click_time) app_4,
device,
LAG(device, 1) OVER(partition by ip order by click_time) device_1,
LAG(device, 2) OVER(partition by ip order by click_time) device_2,
LAG(device, 3) OVER(partition by ip order by click_time) device_3,
LAG(device, 4) OVER(partition by ip order by click_time) device_4,
os,
LAG(os, 1) OVER(partition by ip order by click_time) os_1,
LAG(os, 2) OVER(partition by ip order by click_time) os_2,
LAG(os, 3) OVER(partition by ip order by click_time) os_3,
LAG(os, 4) OVER(partition by ip order by click_time) os_4,
channel,
LAG(channel, 1) OVER(partition by ip order by click_time) channel_1,
LAG(channel, 2) OVER(partition by ip order by click_time) channel_2,
LAG(channel, 3) OVER(partition by ip order by click_time) channel_3,
LAG(channel, 4) OVER(partition by ip order by click_time) channel_4,
is_attributed,
LAG(is_attributed, 1) OVER(partition by ip order by click_time) is_attributed_1,
LAG(is_attributed, 2) OVER(partition by ip order by click_time) is_attributed_2,
LAG(is_attributed, 3) OVER(partition by ip order by click_time) is_attributed_3,
LAG(is_attributed, 4) OVER(partition by ip order by click_time) is_attributed_4,
LAG(is_attributed, 5) OVER(partition by ip order by click_time) is_attributed_5,
hour,
LAG(hour, 1) OVER(partition by ip order by click_time) hour_1,
LAG(hour, 2) OVER(partition by ip order by click_time) hour_2,
LAG(hour, 3) OVER(partition by ip order by click_time) hour_3,
LAG(hour, 4) OVER(partition by ip order by click_time) hour_4,
minute,
LAG(minute, 1) OVER(partition by ip order by click_time) minute_1,
LAG(minute, 2) OVER(partition by ip order by click_time) minute_2,
LAG(minute, 3) OVER(partition by ip order by click_time) minute_3,
LAG(minute, 4) OVER(partition by ip order by click_time) minute_4,
second,
LAG(second, 1) OVER(partition by ip order by click_time) second_1,
LAG(second, 2) OVER(partition by ip order by click_time) second_2,
LAG(second, 3) OVER(partition by ip order by click_time) second_3,
LAG(second, 4) OVER(partition by ip order by click_time) second_4,
avg_app,
LAG(avg_app, 1) OVER(partition by ip order by click_time) avg_app_1,
LAG(avg_app, 2) OVER(partition by ip order by click_time) avg_app_2,
LAG(avg_app, 3) OVER(partition by ip order by click_time) avg_app_3,
LAG(avg_app, 4) OVER(partition by ip order by click_time) avg_app_4,
avg_device,
LAG(avg_device, 1) OVER(partition by ip order by click_time) avg_device_1,
LAG(avg_device, 2) OVER(partition by ip order by click_time) avg_device_2,
LAG(avg_device, 3) OVER(partition by ip order by click_time) avg_device_3,
LAG(avg_device, 4) OVER(partition by ip order by click_time) avg_device_4,
avg_os,
LAG(avg_os, 1) OVER(partition by ip order by click_time) avg_os_1,
LAG(avg_os, 2) OVER(partition by ip order by click_time) avg_os_2,
LAG(avg_os, 3) OVER(partition by ip order by click_time) avg_os_3,
LAG(avg_os, 4) OVER(partition by ip order by click_time) avg_os_4,
avg_channel,
LAG(avg_channel, 1) OVER(partition by ip order by click_time) avg_channel_1,
LAG(avg_channel, 2) OVER(partition by ip order by click_time) avg_channel_2,
LAG(avg_channel, 3) OVER(partition by ip order by click_time) avg_channel_3,
LAG(avg_channel, 4) OVER(partition by ip order by click_time) avg_channel_4,
avg_hour,
LAG(avg_hour, 1) OVER(partition by ip order by click_time) avg_hour_1,
LAG(avg_hour, 2) OVER(partition by ip order by click_time) avg_hour_2,
LAG(avg_hour, 3) OVER(partition by ip order by click_time) avg_hour_3,
LAG(avg_hour, 4) OVER(partition by ip order by click_time) avg_hour_4,
avg_ip_span,
LAG(avg_ip_span, 1) OVER(partition by ip order by click_time) avg_ip_span_1,
LAG(avg_ip_span, 2) OVER(partition by ip order by click_time) avg_ip_span_2,
LAG(avg_ip_span, 3) OVER(partition by ip order by click_time) avg_ip_span_3,
LAG(avg_ip_span, 4) OVER(partition by ip order by click_time) avg_ip_span_4,
avg_minute,
LAG(avg_minute, 1) OVER(partition by ip order by click_time) avg_minute_1,
LAG(avg_minute, 2) OVER(partition by ip order by click_time) avg_minute_2,
LAG(avg_minute, 3) OVER(partition by ip order by click_time) avg_minute_3,
LAG(avg_minute, 4) OVER(partition by ip order by click_time) avg_minute_4,
avg_second,
LAG(avg_second, 1) OVER(partition by ip order by click_time) avg_second_1,
LAG(avg_second, 2) OVER(partition by ip order by click_time) avg_second_2,
LAG(avg_second, 3) OVER(partition by ip order by click_time) avg_second_3,
LAG(avg_second, 4) OVER(partition by ip order by click_time) avg_second_4,
avg_app2,
LAG(avg_app2, 1) OVER(partition by ip order by click_time) avg_app2_1,
LAG(avg_app2, 2) OVER(partition by ip order by click_time) avg_app2_2,
LAG(avg_app2, 3) OVER(partition by ip order by click_time) avg_app2_3,
LAG(avg_app2, 4) OVER(partition by ip order by click_time) avg_app2_4,
avg_device2,
LAG(avg_device2, 1) OVER(partition by ip order by click_time) avg_device2_1,
LAG(avg_device2, 2) OVER(partition by ip order by click_time) avg_device2_2,
LAG(avg_device2, 3) OVER(partition by ip order by click_time) avg_device2_3,
LAG(avg_device2, 4) OVER(partition by ip order by click_time) avg_device2_4,
avg_os2,
LAG(avg_os2, 1) OVER(partition by ip order by click_time) avg_os2_1,
LAG(avg_os2, 2) OVER(partition by ip order by click_time) avg_os2_2,
LAG(avg_os2, 3) OVER(partition by ip order by click_time) avg_os2_3,
LAG(avg_os2, 4) OVER(partition by ip order by click_time) avg_os2_4,
avg_channel2,
LAG(avg_channel2, 1) OVER(partition by ip order by click_time) avg_channel2_1,
LAG(avg_channel2, 2) OVER(partition by ip order by click_time) avg_channel2_2,
LAG(avg_channel2, 3) OVER(partition by ip order by click_time) avg_channel2_3,
LAG(avg_channel2, 4) OVER(partition by ip order by click_time) avg_channel2_4,
avg_hour2,
LAG(avg_hour2, 1) OVER(partition by ip order by click_time) avg_hour2_1,
LAG(avg_hour2, 2) OVER(partition by ip order by click_time) avg_hour2_2,
LAG(avg_hour2, 3) OVER(partition by ip order by click_time) avg_hour2_3,
LAG(avg_hour2, 4) OVER(partition by ip order by click_time) avg_hour2_4,
avg_ip_span2,
LAG(avg_ip_span2, 1) OVER(partition by ip order by click_time) avg_ip_span2_1,
LAG(avg_ip_span2, 2) OVER(partition by ip order by click_time) avg_ip_span2_2,
LAG(avg_ip_span2, 3) OVER(partition by ip order by click_time) avg_ip_span2_3,
LAG(avg_ip_span2, 4) OVER(partition by ip order by click_time) avg_ip_span2_4,
cnt_app,
LAG(cnt_app, 1) OVER(partition by ip order by click_time) cnt_app_1,
LAG(cnt_app, 2) OVER(partition by ip order by click_time) cnt_app_2,
LAG(cnt_app, 3) OVER(partition by ip order by click_time) cnt_app_3,
LAG(cnt_app, 4) OVER(partition by ip order by click_time) cnt_app_4,
cnt_device,
LAG(cnt_device, 1) OVER(partition by ip order by click_time) cnt_device_1,
LAG(cnt_device, 2) OVER(partition by ip order by click_time) cnt_device_2,
LAG(cnt_device, 3) OVER(partition by ip order by click_time) cnt_device_3,
LAG(cnt_device, 4) OVER(partition by ip order by click_time) cnt_device_4,
cnt_os,
LAG(cnt_os, 1) OVER(partition by ip order by click_time) cnt_os_1,
LAG(cnt_os, 2) OVER(partition by ip order by click_time) cnt_os_2,
LAG(cnt_os, 3) OVER(partition by ip order by click_time) cnt_os_3,
LAG(cnt_os, 4) OVER(partition by ip order by click_time) cnt_os_4,
cnt_channel,
LAG(cnt_channel, 1) OVER(partition by ip order by click_time) cnt_channel_1,
LAG(cnt_channel, 2) OVER(partition by ip order by click_time) cnt_channel_2,
LAG(cnt_channel, 3) OVER(partition by ip order by click_time) cnt_channel_3,
LAG(cnt_channel, 4) OVER(partition by ip order by click_time) cnt_channel_4,
cnt_hour,
LAG(cnt_hour, 1) OVER(partition by ip order by click_time) cnt_hour_1,
LAG(cnt_hour, 2) OVER(partition by ip order by click_time) cnt_hour_2,
LAG(cnt_hour, 3) OVER(partition by ip order by click_time) cnt_hour_3,
LAG(cnt_hour, 4) OVER(partition by ip order by click_time) cnt_hour_4,
cnt_ip_span,
LAG(cnt_ip_span, 1) OVER(partition by ip order by click_time) cnt_ip_span_1,
LAG(cnt_ip_span, 2) OVER(partition by ip order by click_time) cnt_ip_span_2,
LAG(cnt_ip_span, 3) OVER(partition by ip order by click_time) cnt_ip_span_3,
LAG(cnt_ip_span, 4) OVER(partition by ip order by click_time) cnt_ip_span_4,
cnt_minute,
LAG(cnt_minute, 1) OVER(partition by ip order by click_time) cnt_minute_1,
LAG(cnt_minute, 2) OVER(partition by ip order by click_time) cnt_minute_2,
LAG(cnt_minute, 3) OVER(partition by ip order by click_time) cnt_minute_3,
LAG(cnt_minute, 4) OVER(partition by ip order by click_time) cnt_minute_4,
cnt_second,
LAG(cnt_second, 1) OVER(partition by ip order by click_time) cnt_second_1,
LAG(cnt_second, 2) OVER(partition by ip order by click_time) cnt_second_2,
LAG(cnt_second, 3) OVER(partition by ip order by click_time) cnt_second_3,
LAG(cnt_second, 4) OVER(partition by ip order by click_time) cnt_second_4,
cnt_app2,
LAG(cnt_app2, 1) OVER(partition by ip order by click_time) cnt_app2_1,
LAG(cnt_app2, 2) OVER(partition by ip order by click_time) cnt_app2_2,
LAG(cnt_app2, 3) OVER(partition by ip order by click_time) cnt_app2_3,
LAG(cnt_app2, 4) OVER(partition by ip order by click_time) cnt_app2_4,
cnt_device2,
LAG(cnt_device2, 1) OVER(partition by ip order by click_time) cnt_device2_1,
LAG(cnt_device2, 2) OVER(partition by ip order by click_time) cnt_device2_2,
LAG(cnt_device2, 3) OVER(partition by ip order by click_time) cnt_device2_3,
LAG(cnt_device2, 4) OVER(partition by ip order by click_time) cnt_device2_4,
cnt_os2,
LAG(cnt_os2, 1) OVER(partition by ip order by click_time) cnt_os2_1,
LAG(cnt_os2, 2) OVER(partition by ip order by click_time) cnt_os2_2,
LAG(cnt_os2, 3) OVER(partition by ip order by click_time) cnt_os2_3,
LAG(cnt_os2, 4) OVER(partition by ip order by click_time) cnt_os2_4,
cnt_channel2,
LAG(cnt_channel2, 1) OVER(partition by ip order by click_time) cnt_channel2_1,
LAG(cnt_channel2, 2) OVER(partition by ip order by click_time) cnt_channel2_2,
LAG(cnt_channel2, 3) OVER(partition by ip order by click_time) cnt_channel2_3,
LAG(cnt_channel2, 4) OVER(partition by ip order by click_time) cnt_channel2_4,
cnt_hour2,
LAG(cnt_hour2, 1) OVER(partition by ip order by click_time) cnt_hour2_1,
LAG(cnt_hour2, 2) OVER(partition by ip order by click_time) cnt_hour2_2,
LAG(cnt_hour2, 3) OVER(partition by ip order by click_time) cnt_hour2_3,
LAG(cnt_hour2, 4) OVER(partition by ip order by click_time) cnt_hour2_4,
cnt_ip_span2,
LAG(cnt_ip_span2, 1) OVER(partition by ip order by click_time) cnt_ip_span2_1,
LAG(cnt_ip_span2, 2) OVER(partition by ip order by click_time) cnt_ip_span2_2,
LAG(cnt_ip_span2, 3) OVER(partition by ip order by click_time) cnt_ip_span2_3,
LAG(cnt_ip_span2, 4) OVER(partition by ip order by click_time) cnt_ip_span2_4
FROM
`talking.train_test3`
WHERE
  day = 8 AND span > 0
